version: "2"

run:
  timeout: 10m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unused
    - unparam
    - revive
  settings:
    gosec:
      excludes:
        - G404
        - G115
    govet:
      disable:
        - printf

  exclusions:
    paths:
      - ".*.pb.go"

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/cometbft/cometbft)
        - prefix(github.com/cosmos)
        - prefix(cosmossdk.io)
        - prefix(github.com/cosmos/cosmos-sdk)
        - prefix(github.com/CosmosContracts/juno)
      custom-order: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
