version: v2

clean: true

inputs:
  # - git_repo: https://github.com/cosmos/ibc-apps.git
  #   tag: middleware/packet-forward-middleware/v8.2.0
  #   subdir: middleware/packet-forward-middleware/proto
  - git_repo: https://github.com/cosmos/cosmos-sdk.git
    tag: v0.50.13
    subdir: proto

plugins:
  - remote: buf.build/community/google-gnostic-openapi:v0.7.0
    out: gen/external
    include_imports: true
    opt:
      - default_response=true
      - fq_schema_naming=false
      - title=Juno REST API
      - version=v30.0.0
      - Mcosmos/app/v1alpha1/module.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/v1alpha1/config.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/v1alpha1/query.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/runtime/v1alpha1/module.proto=cosmossdk.io/api/cosmos/app/runtime/v1alpha1
      - Mcosmos/auth/module/v1/module.proto=cosmossdk.io/api/cosmos/auth/module/v1
      - Mcosmos/authz/module/v1/module.proto=cosmossdk.io/api/cosmos/authz/module/v1
      - Mcosmos/bank/module/v1/module.proto=cosmossdk.io/api/cosmos/bank/module/v1
      - Mcosmos/circuit/module/v1/module.proto=cosmossdk.io/api/cosmos/circuit/module/v1
      - Mcosmos/gov/module/v1/module.proto=cosmossdk.io/api/cosmos/gov/module/v1
      - Mcosmos/consensus/module/v1/module.proto=cosmossdk.io/api/cosmos/consensus/module/v1
      - Mcosmos/crisis/module/v1/module.proto=cosmossdk.io/api/cosmos/crisis/module/v1
      - Mcosmos/distribution/module/v1/module.proto=cosmossdk.io/api/cosmos/distribution/module/v1
      - Mcosmos/evidence/module/v1/module.proto=cosmossdk.io/api/cosmos/evidence/module/v1
      - Mcosmos/feegrant/module/v1/module.proto=cosmossdk.io/api/cosmos/feegrant/module/v1
      - Mcosmos/genutil/module/v1/module.proto=cosmossdk.io/api/cosmos/genutil/module/v1
      - Mcosmos/group/module/v1/module.proto=cosmossdk.io/api/cosmos/group/module/v1
      - Mcosmos/mint/module/v1/module.proto=cosmossdk.io/api/cosmos/mint/module/v1
      - Mcosmos/msg/textual/v1/textual.proto=cosmossdk.io/api/cosmos/msg/textual/v1
      - Mcosmos/nft/module/v1/module.proto=cosmossdk.io/api/cosmos/nft/module/v1
      - Mcosmos/orm/module/v1alpha1/module.proto=cosmossdk.io/api/cosmos/orm/module/v1alpha1
      - Mcosmos/orm/query/v1alpha1/query.proto=cosmossdk.io/api/cosmos/orm/query/v1alpha1
      - Mcosmos/orm/v1/orm.proto=cosmossdk.io/api/cosmos/orm/v1
      - Mcosmos/orm/v1alpha1/schema.proto=cosmossdk.io/api/cosmos/orm/v1alpha1
      - Mcosmos/params/module/v1/module.proto=cosmossdk.io/api/cosmos/params/module/v1
      - Mcosmos/reflection/v1/reflection.proto=cosmossdk.io/api/cosmos/reflection/v1
      - Mcosmos/slashing/module/v1/module.proto=cosmossdk.io/api/cosmos/slashing/module/v1
      - Mcosmos/staking/module/v1/module.proto=cosmossdk.io/api/cosmos/staking/module/v1
      - Mcosmos/tx/config/v1/config.proto=cosmossdk.io/api/cosmos/tx/config/v1
      - Mcosmos/upgrade/module/v1/module.proto=cosmossdk.io/api/cosmos/upgrade/module/v1
      - Mcosmos/vesting/module/v1/module.proto=cosmossdk.io/api/cosmos/vesting/module/v1
      - Mgaia/globalfee/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/gaia/globalfee/module/v1
      - Mjuno/clock/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/juno/clock/module/v1
      - Mjuno/cwhooks/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/juno/cwhooks/module/v1
      - Mjuno/drip/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/drip/clock/module/v1
      - Mjuno/feepay/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/juno/feepay/module/v1
      - Mjuno/feeshare/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/juno/feeshare/module/v1
      - Mjuno/mint/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/juno/mint/module/v1
      - Mosmosis/tokenfactory/module/v1/module.proto=github.com/CosmosContracts/juno/v29/api/osmosis/tokenfactory/module/v1
