// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: juno/votingsnapshot/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryVotingPowerAtRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// at_height is the chain height to look up power for. Named
	// distinctly from `height` so it doesn't collide with cosmos-sdk's
	// standard query --height flag in autocli output.
	AtHeight int64 `protobuf:"varint,2,opt,name=at_height,json=atHeight,proto3" json:"at_height,omitempty"`
}

func (m *QueryVotingPowerAtRequest) Reset()         { *m = QueryVotingPowerAtRequest{} }
func (m *QueryVotingPowerAtRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerAtRequest) ProtoMessage()    {}
func (*QueryVotingPowerAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{2}
}
func (m *QueryVotingPowerAtRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerAtRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerAtRequest.Merge(m, src)
}
func (m *QueryVotingPowerAtRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerAtRequest proto.InternalMessageInfo

func (m *QueryVotingPowerAtRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryVotingPowerAtRequest) GetAtHeight() int64 {
	if m != nil {
		return m.AtHeight
	}
	return 0
}

type QueryVotingPowerAtResponse struct {
	// power is the bonded stake amount as a base-10 string (uint).
	Power string `protobuf:"bytes,1,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *QueryVotingPowerAtResponse) Reset()         { *m = QueryVotingPowerAtResponse{} }
func (m *QueryVotingPowerAtResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerAtResponse) ProtoMessage()    {}
func (*QueryVotingPowerAtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{3}
}
func (m *QueryVotingPowerAtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerAtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerAtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerAtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerAtResponse.Merge(m, src)
}
func (m *QueryVotingPowerAtResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerAtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerAtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerAtResponse proto.InternalMessageInfo

func (m *QueryVotingPowerAtResponse) GetPower() string {
	if m != nil {
		return m.Power
	}
	return ""
}

type QueryTotalVotingPowerAtRequest struct {
	AtHeight int64 `protobuf:"varint,1,opt,name=at_height,json=atHeight,proto3" json:"at_height,omitempty"`
}

func (m *QueryTotalVotingPowerAtRequest) Reset()         { *m = QueryTotalVotingPowerAtRequest{} }
func (m *QueryTotalVotingPowerAtRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVotingPowerAtRequest) ProtoMessage()    {}
func (*QueryTotalVotingPowerAtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{4}
}
func (m *QueryTotalVotingPowerAtRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVotingPowerAtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVotingPowerAtRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVotingPowerAtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVotingPowerAtRequest.Merge(m, src)
}
func (m *QueryTotalVotingPowerAtRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVotingPowerAtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVotingPowerAtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVotingPowerAtRequest proto.InternalMessageInfo

func (m *QueryTotalVotingPowerAtRequest) GetAtHeight() int64 {
	if m != nil {
		return m.AtHeight
	}
	return 0
}

type QueryTotalVotingPowerAtResponse struct {
	Power string `protobuf:"bytes,1,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *QueryTotalVotingPowerAtResponse) Reset()         { *m = QueryTotalVotingPowerAtResponse{} }
func (m *QueryTotalVotingPowerAtResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTotalVotingPowerAtResponse) ProtoMessage()    {}
func (*QueryTotalVotingPowerAtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{5}
}
func (m *QueryTotalVotingPowerAtResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTotalVotingPowerAtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTotalVotingPowerAtResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTotalVotingPowerAtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalVotingPowerAtResponse.Merge(m, src)
}
func (m *QueryTotalVotingPowerAtResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTotalVotingPowerAtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalVotingPowerAtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalVotingPowerAtResponse proto.InternalMessageInfo

func (m *QueryTotalVotingPowerAtResponse) GetPower() string {
	if m != nil {
		return m.Power
	}
	return ""
}

type QueryVotingPowerOverRangeRequest struct {
	Address    string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	FromHeight int64  `protobuf:"varint,2,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight   int64  `protobuf:"varint,3,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
}

func (m *QueryVotingPowerOverRangeRequest) Reset()         { *m = QueryVotingPowerOverRangeRequest{} }
func (m *QueryVotingPowerOverRangeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerOverRangeRequest) ProtoMessage()    {}
func (*QueryVotingPowerOverRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{6}
}
func (m *QueryVotingPowerOverRangeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerOverRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerOverRangeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerOverRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerOverRangeRequest.Merge(m, src)
}
func (m *QueryVotingPowerOverRangeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerOverRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerOverRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerOverRangeRequest proto.InternalMessageInfo

func (m *QueryVotingPowerOverRangeRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *QueryVotingPowerOverRangeRequest) GetFromHeight() int64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *QueryVotingPowerOverRangeRequest) GetToHeight() int64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

type QueryVotingPowerOverRangeResponse struct {
	Rows []HeightPower `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows"`
}

func (m *QueryVotingPowerOverRangeResponse) Reset()         { *m = QueryVotingPowerOverRangeResponse{} }
func (m *QueryVotingPowerOverRangeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVotingPowerOverRangeResponse) ProtoMessage()    {}
func (*QueryVotingPowerOverRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{7}
}
func (m *QueryVotingPowerOverRangeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVotingPowerOverRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVotingPowerOverRangeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVotingPowerOverRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVotingPowerOverRangeResponse.Merge(m, src)
}
func (m *QueryVotingPowerOverRangeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVotingPowerOverRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVotingPowerOverRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVotingPowerOverRangeResponse proto.InternalMessageInfo

func (m *QueryVotingPowerOverRangeResponse) GetRows() []HeightPower {
	if m != nil {
		return m.Rows
	}
	return nil
}

type HeightPower struct {
	Height int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Power  string `protobuf:"bytes,2,opt,name=power,proto3" json:"power,omitempty"`
}

func (m *HeightPower) Reset()         { *m = HeightPower{} }
func (m *HeightPower) String() string { return proto.CompactTextString(m) }
func (*HeightPower) ProtoMessage()    {}
func (*HeightPower) Descriptor() ([]byte, []int) {
	return fileDescriptor_b21e040e5054d3f1, []int{8}
}
func (m *HeightPower) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeightPower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeightPower.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeightPower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeightPower.Merge(m, src)
}
func (m *HeightPower) XXX_Size() int {
	return m.Size()
}
func (m *HeightPower) XXX_DiscardUnknown() {
	xxx_messageInfo_HeightPower.DiscardUnknown(m)
}

var xxx_messageInfo_HeightPower proto.InternalMessageInfo

func (m *HeightPower) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HeightPower) GetPower() string {
	if m != nil {
		return m.Power
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "juno.votingsnapshot.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "juno.votingsnapshot.v1.QueryParamsResponse")
	proto.RegisterType((*QueryVotingPowerAtRequest)(nil), "juno.votingsnapshot.v1.QueryVotingPowerAtRequest")
	proto.RegisterType((*QueryVotingPowerAtResponse)(nil), "juno.votingsnapshot.v1.QueryVotingPowerAtResponse")
	proto.RegisterType((*QueryTotalVotingPowerAtRequest)(nil), "juno.votingsnapshot.v1.QueryTotalVotingPowerAtRequest")
	proto.RegisterType((*QueryTotalVotingPowerAtResponse)(nil), "juno.votingsnapshot.v1.QueryTotalVotingPowerAtResponse")
	proto.RegisterType((*QueryVotingPowerOverRangeRequest)(nil), "juno.votingsnapshot.v1.QueryVotingPowerOverRangeRequest")
	proto.RegisterType((*QueryVotingPowerOverRangeResponse)(nil), "juno.votingsnapshot.v1.QueryVotingPowerOverRangeResponse")
	proto.RegisterType((*HeightPower)(nil), "juno.votingsnapshot.v1.HeightPower")
}

func init() {
	proto.RegisterFile("juno/votingsnapshot/v1/query.proto", fileDescriptor_b21e040e5054d3f1)
}

var fileDescriptor_b21e040e5054d3f1 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0xfb, 0x11, 0xe8, 0x44, 0x5c, 0x96, 0xa8, 0x0a, 0x06, 0x39, 0xc1, 0x95, 0x50, 0x04,
	0xc2, 0x4b, 0x52, 0xa9, 0x2d, 0xb4, 0x45, 0x22, 0xbd, 0x70, 0x82, 0x60, 0xa0, 0x07, 0x2e, 0xd1,
	0xa6, 0x35, 0x4e, 0x50, 0xe3, 0x71, 0xed, 0x4d, 0x4a, 0x89, 0x72, 0xe1, 0xc6, 0x0d, 0x89, 0x7f,
	0xc3, 0x1d, 0xa9, 0xc7, 0x4a, 0x5c, 0x38, 0x21, 0x94, 0xf0, 0x3b, 0x10, 0xf2, 0xee, 0x36, 0x8d,
	0xd3, 0x38, 0x34, 0xdc, 0xbc, 0xb3, 0xf3, 0xe6, 0xbd, 0x37, 0x3b, 0x63, 0x30, 0xdf, 0xb5, 0x3d,
	0xa4, 0x1d, 0xe4, 0x4d, 0xcf, 0x0d, 0x3d, 0xe6, 0x87, 0x0d, 0xe4, 0xb4, 0x53, 0xa2, 0x87, 0x6d,
	0x27, 0x38, 0xb6, 0xfc, 0x00, 0x39, 0x92, 0xe5, 0x28, 0xc7, 0x8a, 0xe7, 0x58, 0x9d, 0x92, 0x9e,
	0x75, 0xd1, 0x45, 0x91, 0x42, 0xa3, 0x2f, 0x99, 0xad, 0xdf, 0x72, 0x11, 0xdd, 0x03, 0x87, 0x32,
	0xbf, 0x49, 0x99, 0xe7, 0x21, 0x67, 0xbc, 0x89, 0x5e, 0xa8, 0x6e, 0x57, 0x12, 0xf8, 0x7c, 0x16,
	0xb0, 0x96, 0x4a, 0x32, 0xb3, 0x40, 0x5e, 0x44, 0xfc, 0x55, 0x11, 0xb4, 0x9d, 0xc3, 0xb6, 0x13,
	0x72, 0xf3, 0x25, 0x5c, 0x8f, 0x45, 0x43, 0x1f, 0xbd, 0xd0, 0x21, 0x5b, 0x90, 0x96, 0xe0, 0x9c,
	0x56, 0xd0, 0x8a, 0x99, 0xb2, 0x61, 0x4d, 0x96, 0x6b, 0x49, 0x5c, 0x65, 0xe1, 0xe4, 0x67, 0x3e,
	0x65, 0x2b, 0x8c, 0x69, 0xc3, 0x0d, 0x51, 0x74, 0x57, 0xa4, 0x57, 0xf1, 0xc8, 0x09, 0x9e, 0x70,
	0xc5, 0x48, 0x72, 0x70, 0x85, 0xed, 0xef, 0x07, 0x4e, 0x28, 0x6b, 0x2f, 0xd9, 0x67, 0x47, 0x72,
	0x13, 0x96, 0x18, 0xaf, 0x35, 0x9c, 0xa6, 0xdb, 0xe0, 0xb9, 0xb9, 0x82, 0x56, 0x9c, 0xb7, 0xaf,
	0x32, 0xfe, 0x54, 0x9c, 0xcd, 0x32, 0xe8, 0x93, 0x6a, 0x2a, 0xbd, 0x59, 0x58, 0xf4, 0xa3, 0x90,
	0x2a, 0x29, 0x0f, 0xe6, 0x36, 0x18, 0x02, 0xf3, 0x0a, 0x39, 0x3b, 0x98, 0x28, 0x26, 0x46, 0xa9,
	0x8d, 0x51, 0xae, 0x43, 0x3e, 0x11, 0x3e, 0x95, 0xf7, 0x03, 0x14, 0xc6, 0xb5, 0x3e, 0xef, 0x38,
	0x81, 0xcd, 0x3c, 0xd7, 0xf9, 0x77, 0x1b, 0xf2, 0x90, 0x79, 0x1b, 0x60, 0x2b, 0xde, 0x08, 0x88,
	0x42, 0x52, 0x57, 0x24, 0x9a, 0xe3, 0xd9, 0xf5, 0xbc, 0x14, 0xcd, 0x51, 0x89, 0xae, 0xc3, 0xed,
	0x29, 0xdc, 0x4a, 0xf6, 0x36, 0x2c, 0x04, 0x78, 0x14, 0x31, 0xcf, 0x17, 0x33, 0xe5, 0x95, 0xa4,
	0xc7, 0x95, 0x25, 0x45, 0x0d, 0xf5, 0xc2, 0x02, 0x66, 0x6e, 0x42, 0x66, 0xe4, 0x8a, 0x2c, 0x43,
	0x3a, 0xd6, 0x41, 0x75, 0x3a, 0x6f, 0xce, 0xdc, 0x48, 0x73, 0xca, 0x7f, 0x16, 0x61, 0x51, 0x28,
	0x24, 0x9f, 0x34, 0x48, 0xcb, 0xf9, 0x21, 0x77, 0x93, 0x24, 0x5c, 0x1c, 0x59, 0xfd, 0xde, 0xa5,
	0x72, 0xa5, 0x53, 0xf3, 0xce, 0xc7, 0xef, 0xbf, 0xbf, 0xcc, 0x15, 0x88, 0x41, 0xa7, 0xee, 0x08,
	0xf9, 0xaa, 0xc1, 0xb5, 0xd8, 0x13, 0x93, 0xd2, 0x54, 0x9a, 0x49, 0xd3, 0xa4, 0x97, 0x67, 0x81,
	0x28, 0x81, 0x15, 0x21, 0x70, 0x8b, 0x3c, 0x4a, 0x12, 0x28, 0x23, 0x35, 0xd1, 0x3c, 0xda, 0x55,
	0x43, 0xd2, 0xa3, 0xdd, 0xe1, 0xdc, 0xf6, 0xc8, 0x37, 0x0d, 0xc8, 0xc5, 0x21, 0x25, 0x6b, 0x53,
	0xe5, 0x24, 0x2e, 0x85, 0xbe, 0x3e, 0x33, 0x4e, 0x79, 0x79, 0x2c, 0xbc, 0x6c, 0x90, 0xb5, 0x24,
	0x2f, 0x3c, 0xc2, 0xd6, 0xc6, 0x1c, 0x9d, 0xfb, 0x18, 0x68, 0x90, 0x9d, 0x34, 0xb7, 0x64, 0xe3,
	0xb2, 0x8d, 0x1d, 0x5f, 0x33, 0xfd, 0xe1, 0x7f, 0x20, 0x95, 0x9b, 0x5d, 0xe1, 0xa6, 0x4a, 0x9e,
	0xcd, 0xf8, 0x32, 0x41, 0x54, 0x85, 0x76, 0x47, 0x76, 0xb8, 0x47, 0xbb, 0xc3, 0x85, 0xed, 0x55,
	0x5e, 0x9f, 0xf4, 0x0d, 0xed, 0xb4, 0x6f, 0x68, 0xbf, 0xfa, 0x86, 0xf6, 0x79, 0x60, 0xa4, 0x4e,
	0x07, 0x46, 0xea, 0xc7, 0xc0, 0x48, 0xbd, 0xd9, 0x74, 0x9b, 0xbc, 0xd1, 0xae, 0x5b, 0x7b, 0xd8,
	0xa2, 0x3b, 0x18, 0xb6, 0x30, 0xdc, 0x41, 0x8f, 0x07, 0x6c, 0x8f, 0x87, 0x4a, 0xc3, 0xea, 0x03,
	0xfa, 0x5e, 0xf1, 0xde, 0x1f, 0x4a, 0xe1, 0xc7, 0xbe, 0x13, 0xd6, 0xd3, 0xe2, 0x37, 0xbf, 0xfa,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x10, 0x6e, 0x4e, 0x7d, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the current x/voting-snapshot module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// VotingPowerAt returns the bonded voting power of `address` at
	// `at_height`, excluding LST-held delegations. Resolves to the
	// most recent snapshot at-or-before the requested height. Returns
	// zero (with no error) if no snapshot exists.
	VotingPowerAt(ctx context.Context, in *QueryVotingPowerAtRequest, opts ...grpc.CallOption) (*QueryVotingPowerAtResponse, error)
	// TotalVotingPowerAt returns the chain-wide bonded supply at
	// `at_height`. Same at-or-before semantics as VotingPowerAt.
	TotalVotingPowerAt(ctx context.Context, in *QueryTotalVotingPowerAtRequest, opts ...grpc.CallOption) (*QueryTotalVotingPowerAtResponse, error)
	// VotingPowerOverRange returns every recorded snapshot for `address`
	// in [from_height, to_height]. Useful for time-decay schemes.
	VotingPowerOverRange(ctx context.Context, in *QueryVotingPowerOverRangeRequest, opts ...grpc.CallOption) (*QueryVotingPowerOverRangeResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/juno.votingsnapshot.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VotingPowerAt(ctx context.Context, in *QueryVotingPowerAtRequest, opts ...grpc.CallOption) (*QueryVotingPowerAtResponse, error) {
	out := new(QueryVotingPowerAtResponse)
	err := c.cc.Invoke(ctx, "/juno.votingsnapshot.v1.Query/VotingPowerAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TotalVotingPowerAt(ctx context.Context, in *QueryTotalVotingPowerAtRequest, opts ...grpc.CallOption) (*QueryTotalVotingPowerAtResponse, error) {
	out := new(QueryTotalVotingPowerAtResponse)
	err := c.cc.Invoke(ctx, "/juno.votingsnapshot.v1.Query/TotalVotingPowerAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VotingPowerOverRange(ctx context.Context, in *QueryVotingPowerOverRangeRequest, opts ...grpc.CallOption) (*QueryVotingPowerOverRangeResponse, error) {
	out := new(QueryVotingPowerOverRangeResponse)
	err := c.cc.Invoke(ctx, "/juno.votingsnapshot.v1.Query/VotingPowerOverRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the current x/voting-snapshot module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// VotingPowerAt returns the bonded voting power of `address` at
	// `at_height`, excluding LST-held delegations. Resolves to the
	// most recent snapshot at-or-before the requested height. Returns
	// zero (with no error) if no snapshot exists.
	VotingPowerAt(context.Context, *QueryVotingPowerAtRequest) (*QueryVotingPowerAtResponse, error)
	// TotalVotingPowerAt returns the chain-wide bonded supply at
	// `at_height`. Same at-or-before semantics as VotingPowerAt.
	TotalVotingPowerAt(context.Context, *QueryTotalVotingPowerAtRequest) (*QueryTotalVotingPowerAtResponse, error)
	// VotingPowerOverRange returns every recorded snapshot for `address`
	// in [from_height, to_height]. Useful for time-decay schemes.
	VotingPowerOverRange(context.Context, *QueryVotingPowerOverRangeRequest) (*QueryVotingPowerOverRangeResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) VotingPowerAt(ctx context.Context, req *QueryVotingPowerAtRequest) (*QueryVotingPowerAtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VotingPowerAt not implemented")
}
func (*UnimplementedQueryServer) TotalVotingPowerAt(ctx context.Context, req *QueryTotalVotingPowerAtRequest) (*QueryTotalVotingPowerAtResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TotalVotingPowerAt not implemented")
}
func (*UnimplementedQueryServer) VotingPowerOverRange(ctx context.Context, req *QueryVotingPowerOverRangeRequest) (*QueryVotingPowerOverRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VotingPowerOverRange not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.votingsnapshot.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VotingPowerAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVotingPowerAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VotingPowerAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.votingsnapshot.v1.Query/VotingPowerAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VotingPowerAt(ctx, req.(*QueryVotingPowerAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TotalVotingPowerAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTotalVotingPowerAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TotalVotingPowerAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.votingsnapshot.v1.Query/TotalVotingPowerAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TotalVotingPowerAt(ctx, req.(*QueryTotalVotingPowerAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VotingPowerOverRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVotingPowerOverRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VotingPowerOverRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.votingsnapshot.v1.Query/VotingPowerOverRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VotingPowerOverRange(ctx, req.(*QueryVotingPowerOverRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juno.votingsnapshot.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "VotingPowerAt",
			Handler:    _Query_VotingPowerAt_Handler,
		},
		{
			MethodName: "TotalVotingPowerAt",
			Handler:    _Query_TotalVotingPowerAt_Handler,
		},
		{
			MethodName: "VotingPowerOverRange",
			Handler:    _Query_VotingPowerOverRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/votingsnapshot/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerAtRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerAtRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerAtRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AtHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerAtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerAtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerAtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Power) > 0 {
		i -= len(m.Power)
		copy(dAtA[i:], m.Power)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Power)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalVotingPowerAtRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVotingPowerAtRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVotingPowerAtRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AtHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AtHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryTotalVotingPowerAtResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTotalVotingPowerAtResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTotalVotingPowerAtResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Power) > 0 {
		i -= len(m.Power)
		copy(dAtA[i:], m.Power)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Power)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerOverRangeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerOverRangeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerOverRangeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ToHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ToHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.FromHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.FromHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVotingPowerOverRangeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVotingPowerOverRangeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVotingPowerOverRangeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rows) > 0 {
		for iNdEx := len(m.Rows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *HeightPower) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeightPower) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeightPower) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Power) > 0 {
		i -= len(m.Power)
		copy(dAtA[i:], m.Power)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Power)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryVotingPowerAtRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AtHeight != 0 {
		n += 1 + sovQuery(uint64(m.AtHeight))
	}
	return n
}

func (m *QueryVotingPowerAtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Power)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTotalVotingPowerAtRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AtHeight != 0 {
		n += 1 + sovQuery(uint64(m.AtHeight))
	}
	return n
}

func (m *QueryTotalVotingPowerAtResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Power)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVotingPowerOverRangeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.FromHeight != 0 {
		n += 1 + sovQuery(uint64(m.FromHeight))
	}
	if m.ToHeight != 0 {
		n += 1 + sovQuery(uint64(m.ToHeight))
	}
	return n
}

func (m *QueryVotingPowerOverRangeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *HeightPower) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovQuery(uint64(m.Height))
	}
	l = len(m.Power)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerAtRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerAtRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerAtRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtHeight", wireType)
			}
			m.AtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerAtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerAtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerAtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Power = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalVotingPowerAtRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVotingPowerAtRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVotingPowerAtRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtHeight", wireType)
			}
			m.AtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTotalVotingPowerAtResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTotalVotingPowerAtResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTotalVotingPowerAtResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Power = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerOverRangeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerOverRangeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerOverRangeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromHeight", wireType)
			}
			m.FromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToHeight", wireType)
			}
			m.ToHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ToHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVotingPowerOverRangeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVotingPowerOverRangeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVotingPowerOverRangeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, HeightPower{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeightPower) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeightPower: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeightPower: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Power", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Power = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
