// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/globalfee/v1beta1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryMinimumGasPricesRequest is the request type for the
// Query/MinimumGasPrices RPC method.
type QueryMinimumGasPricesRequest struct {
}

func (m *QueryMinimumGasPricesRequest) Reset()         { *m = QueryMinimumGasPricesRequest{} }
func (m *QueryMinimumGasPricesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMinimumGasPricesRequest) ProtoMessage()    {}
func (*QueryMinimumGasPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a736cede25d10a, []int{0}
}
func (m *QueryMinimumGasPricesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMinimumGasPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMinimumGasPricesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMinimumGasPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMinimumGasPricesRequest.Merge(m, src)
}
func (m *QueryMinimumGasPricesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMinimumGasPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMinimumGasPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMinimumGasPricesRequest proto.InternalMessageInfo

// QueryMinimumGasPricesResponse is the response type for the
// Query/MinimumGasPrices RPC method.
type QueryMinimumGasPricesResponse struct {
	MinimumGasPrices github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,1,rep,name=minimum_gas_prices,json=minimumGasPrices,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"minimum_gas_prices"`
}

func (m *QueryMinimumGasPricesResponse) Reset()         { *m = QueryMinimumGasPricesResponse{} }
func (m *QueryMinimumGasPricesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMinimumGasPricesResponse) ProtoMessage()    {}
func (*QueryMinimumGasPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12a736cede25d10a, []int{1}
}
func (m *QueryMinimumGasPricesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMinimumGasPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMinimumGasPricesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMinimumGasPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMinimumGasPricesResponse.Merge(m, src)
}
func (m *QueryMinimumGasPricesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMinimumGasPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMinimumGasPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMinimumGasPricesResponse proto.InternalMessageInfo

func (m *QueryMinimumGasPricesResponse) GetMinimumGasPrices() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.MinimumGasPrices
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryMinimumGasPricesRequest)(nil), "gaia.globalfee.v1beta1.QueryMinimumGasPricesRequest")
	proto.RegisterType((*QueryMinimumGasPricesResponse)(nil), "gaia.globalfee.v1beta1.QueryMinimumGasPricesResponse")
}

func init() {
	proto.RegisterFile("gaia/globalfee/v1beta1/query.proto", fileDescriptor_12a736cede25d10a)
}

var fileDescriptor_12a736cede25d10a = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xb1, 0x4b, 0xfb, 0x40,
	0x14, 0xce, 0xfd, 0x7e, 0xe8, 0x10, 0x97, 0x1a, 0x44, 0xa4, 0xd4, 0xab, 0x64, 0x2a, 0x55, 0xef,
	0x68, 0x55, 0x70, 0xae, 0x82, 0x93, 0xa0, 0x1d, 0x5d, 0xca, 0x25, 0x9e, 0xe7, 0x61, 0x73, 0x2f,
	0xed, 0x25, 0x62, 0x57, 0xf1, 0x0f, 0x10, 0xfc, 0x1f, 0x44, 0x9c, 0x04, 0x67, 0xf7, 0x8e, 0x05,
	0x17, 0x27, 0x95, 0x56, 0xf0, 0xdf, 0x90, 0x5c, 0x52, 0x95, 0xd6, 0x0a, 0x2e, 0xc9, 0xe3, 0xbe,
	0xef, 0xbd, 0xef, 0x7b, 0xdf, 0x9d, 0xed, 0x0a, 0x26, 0x19, 0x15, 0x4d, 0xf0, 0x58, 0xf3, 0x88,
	0x73, 0x7a, 0x5a, 0xf1, 0x78, 0xc4, 0x2a, 0xb4, 0x15, 0xf3, 0x76, 0x87, 0x84, 0x6d, 0x88, 0xc0,
	0x99, 0x4f, 0x38, 0xe4, 0x93, 0x43, 0x32, 0x4e, 0x7e, 0x96, 0x05, 0x52, 0x01, 0x35, 0xdf, 0x94,
	0x9a, 0x9f, 0x13, 0x20, 0xc0, 0x94, 0x34, 0xa9, 0xb2, 0xd3, 0x82, 0x00, 0x10, 0x4d, 0x4e, 0x59,
	0x28, 0x29, 0x53, 0x0a, 0x22, 0x16, 0x49, 0x50, 0x3a, 0x43, 0xb1, 0x0f, 0x3a, 0x00, 0x4d, 0x3d,
	0xa6, 0xbf, 0xf4, 0x7d, 0x90, 0x2a, 0xc5, 0x5d, 0x6c, 0x17, 0xf6, 0x13, 0x37, 0xbb, 0x52, 0xc9,
	0x20, 0x0e, 0x76, 0x98, 0xde, 0x6b, 0x4b, 0x9f, 0xeb, 0x3a, 0x6f, 0xc5, 0x5c, 0x47, 0xee, 0x35,
	0xb2, 0x17, 0x27, 0x10, 0x74, 0x08, 0x4a, 0x73, 0xe7, 0x02, 0xd9, 0x4e, 0x90, 0x82, 0x0d, 0xc1,
	0x74, 0x23, 0x34, 0xf0, 0x02, 0x5a, 0xfa, 0x5f, 0x9a, 0xa9, 0x16, 0x48, 0xaa, 0x4f, 0x12, 0xfd,
	0xe1, 0x6e, 0x64, 0x9b, 0xfb, 0x5b, 0x20, 0x55, 0x6d, 0xb3, 0xfb, 0x5c, 0xb4, 0x6e, 0x5f, 0x8a,
	0xcb, 0x42, 0x46, 0xc7, 0xb1, 0x47, 0x7c, 0x08, 0x68, 0xe6, 0x37, 0xfd, 0xad, 0xea, 0xc3, 0x13,
	0x1a, 0x75, 0x42, 0xae, 0x87, 0x3d, 0xfa, 0xe6, 0xfd, 0xae, 0x8c, 0xea, 0xb9, 0x60, 0xc4, 0x4e,
	0xf5, 0x01, 0xd9, 0x53, 0xc6, 0xa8, 0x73, 0x8f, 0xec, 0xdc, 0xa8, 0x5b, 0x67, 0x9d, 0xfc, 0x9c,
	0x33, 0xf9, 0x6d, 0xfb, 0xfc, 0xc6, 0x1f, 0xbb, 0xd2, 0x48, 0xdc, 0xea, 0xf9, 0xe3, 0xdb, 0xd5,
	0xbf, 0x15, 0xa7, 0x4c, 0x27, 0x3c, 0x80, 0xf1, 0xbc, 0x6a, 0xb5, 0x6e, 0x1f, 0xa3, 0x5e, 0x1f,
	0xa3, 0xd7, 0x3e, 0x46, 0x97, 0x03, 0x6c, 0xf5, 0x06, 0xd8, 0x7a, 0x1a, 0x60, 0xeb, 0xa0, 0x34,
	0x9e, 0x8e, 0x19, 0x7b, 0xf6, 0x6d, 0xb0, 0xc9, 0xc8, 0x9b, 0x36, 0x77, 0xba, 0xf6, 0x11, 0x00,
	0x00, 0xff, 0xff, 0x48, 0x52, 0xef, 0xb9, 0x78, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// MinimumGasPrices queries the minimum gas prices.
	MinimumGasPrices(ctx context.Context, in *QueryMinimumGasPricesRequest, opts ...grpc.CallOption) (*QueryMinimumGasPricesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) MinimumGasPrices(ctx context.Context, in *QueryMinimumGasPricesRequest, opts ...grpc.CallOption) (*QueryMinimumGasPricesResponse, error) {
	out := new(QueryMinimumGasPricesResponse)
	err := c.cc.Invoke(ctx, "/gaia.globalfee.v1beta1.Query/MinimumGasPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// MinimumGasPrices queries the minimum gas prices.
	MinimumGasPrices(context.Context, *QueryMinimumGasPricesRequest) (*QueryMinimumGasPricesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) MinimumGasPrices(ctx context.Context, req *QueryMinimumGasPricesRequest) (*QueryMinimumGasPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MinimumGasPrices not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_MinimumGasPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMinimumGasPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MinimumGasPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gaia.globalfee.v1beta1.Query/MinimumGasPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MinimumGasPrices(ctx, req.(*QueryMinimumGasPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gaia.globalfee.v1beta1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MinimumGasPrices",
			Handler:    _Query_MinimumGasPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gaia/globalfee/v1beta1/query.proto",
}

func (m *QueryMinimumGasPricesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMinimumGasPricesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMinimumGasPricesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryMinimumGasPricesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMinimumGasPricesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMinimumGasPricesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinimumGasPrices) > 0 {
		for iNdEx := len(m.MinimumGasPrices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MinimumGasPrices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryMinimumGasPricesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryMinimumGasPricesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MinimumGasPrices) > 0 {
		for _, e := range m.MinimumGasPrices {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryMinimumGasPricesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMinimumGasPricesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMinimumGasPricesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMinimumGasPricesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMinimumGasPricesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMinimumGasPricesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumGasPrices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinimumGasPrices = append(m.MinimumGasPrices, types.DecCoin{})
			if err := m.MinimumGasPrices[len(m.MinimumGasPrices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
