// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: juno/cwhooks/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState - initial state of module
type GenesisState struct {
	// Params of this module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// staking_contract_addresses
	StakingContractAddresses []string `protobuf:"bytes,2,rep,name=staking_contract_addresses,json=stakingContractAddresses,proto3" json:"staking_contract_addresses,omitempty" yaml:"staking_contract_addresses"`
	// gov_contract_addresses
	GovContractAddresses []string `protobuf:"bytes,3,rep,name=gov_contract_addresses,json=govContractAddresses,proto3" json:"gov_contract_addresses,omitempty" yaml:"gov_contract_addresses"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d384a01656df5cd8, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetStakingContractAddresses() []string {
	if m != nil {
		return m.StakingContractAddresses
	}
	return nil
}

func (m *GenesisState) GetGovContractAddresses() []string {
	if m != nil {
		return m.GovContractAddresses
	}
	return nil
}

// Params defines the set of module parameters.
type Params struct {
	// contract_gas_limit is the contract call gas limit
	ContractGasLimit uint64 `protobuf:"varint,1,opt,name=contract_gas_limit,json=contractGasLimit,proto3" json:"contract_gas_limit,omitempty" yaml:"contract_gas_limit"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_d384a01656df5cd8, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetContractGasLimit() uint64 {
	if m != nil {
		return m.ContractGasLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "juno.cwhooks.v1.GenesisState")
	proto.RegisterType((*Params)(nil), "juno.cwhooks.v1.Params")
}

func init() { proto.RegisterFile("juno/cwhooks/v1/genesis.proto", fileDescriptor_d384a01656df5cd8) }

var fileDescriptor_d384a01656df5cd8 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xc1, 0x4a, 0xeb, 0x40,
	0x18, 0x85, 0x93, 0xf6, 0x52, 0xb8, 0xb9, 0x17, 0x2c, 0xa1, 0x68, 0x2c, 0x36, 0xa9, 0xc1, 0x45,
	0x17, 0x9a, 0x31, 0xba, 0x13, 0x5c, 0x98, 0x22, 0x45, 0x51, 0x90, 0xb8, 0x73, 0x53, 0x26, 0xe9,
	0x30, 0x8d, 0x6d, 0x32, 0x21, 0x33, 0x4d, 0x2d, 0x3e, 0x82, 0x1b, 0x1f, 0xab, 0xcb, 0x2e, 0x5d,
	0x05, 0x69, 0x5d, 0x65, 0xe9, 0x13, 0x48, 0x33, 0xa9, 0x52, 0xdb, 0xee, 0x86, 0xff, 0x3b, 0xf3,
	0x9f, 0xc3, 0xcf, 0x91, 0x6a, 0x8f, 0x83, 0x80, 0x00, 0x77, 0xd8, 0x25, 0xa4, 0x47, 0x41, 0x6c,
	0x02, 0x8c, 0x02, 0x44, 0x3d, 0x6a, 0x84, 0x11, 0x61, 0x44, 0xde, 0x9a, 0x63, 0x23, 0xc7, 0x46,
	0x6c, 0x56, 0x2b, 0x98, 0x60, 0x92, 0x31, 0x30, 0x7f, 0x71, 0x59, 0x55, 0x75, 0x09, 0xf5, 0x09,
	0x05, 0x0e, 0xa4, 0x08, 0xc4, 0xa6, 0x83, 0x18, 0x34, 0x81, 0x4b, 0xbc, 0x80, 0x73, 0xfd, 0xa3,
	0x20, 0xfd, 0x6f, 0xf1, 0xc5, 0xf7, 0x0c, 0x32, 0x24, 0x5f, 0x49, 0xa5, 0x10, 0x46, 0xd0, 0xa7,
	0x8a, 0x58, 0x17, 0x1b, 0xff, 0x4e, 0x76, 0x8c, 0x5f, 0x46, 0xc6, 0x5d, 0x86, 0x2d, 0x65, 0x9c,
	0x68, 0x42, 0x9a, 0x68, 0x65, 0x2e, 0x3f, 0x24, 0xbe, 0xc7, 0x90, 0x1f, 0xb2, 0x91, 0x9d, 0x2f,
	0x90, 0x5f, 0x44, 0xa9, 0x4a, 0x19, 0xec, 0x79, 0x01, 0x6e, 0xbb, 0x24, 0x60, 0x11, 0x74, 0x59,
	0x1b, 0x76, 0x3a, 0x11, 0xa2, 0x14, 0x51, 0xa5, 0x50, 0x2f, 0x36, 0xfe, 0x5a, 0xb7, 0x69, 0xa2,
	0x1d, 0x6c, 0x56, 0xfd, 0xac, 0xfd, 0x4c, 0xb4, 0xfd, 0x11, 0xf4, 0xfb, 0x67, 0xfa, 0x66, 0xb5,
	0x6e, 0x2b, 0x39, 0x6c, 0xe6, 0xec, 0x62, 0x81, 0xe4, 0x67, 0x69, 0x1b, 0x93, 0x78, 0x5d, 0x90,
	0x62, 0x16, 0xe4, 0x32, 0x4d, 0xb4, 0xfa, 0x7a, 0xc5, 0x52, 0x88, 0x1a, 0x0f, 0xb1, 0x5e, 0xa9,
	0xdb, 0x15, 0x4c, 0xe2, 0x15, 0x73, 0x7d, 0x20, 0x95, 0xf8, 0xd9, 0xe4, 0x9e, 0x24, 0x7f, 0x7f,
	0xc3, 0x90, 0xb6, 0xfb, 0x9e, 0xef, 0xb1, 0xec, 0xd6, 0x7f, 0xac, 0xf3, 0x34, 0xd1, 0xf6, 0x56,
	0xe9, 0x92, 0xfd, 0x2e, 0xb7, 0x5f, 0x55, 0xe9, 0x76, 0x79, 0x31, 0x6c, 0x41, 0x7a, 0x33, 0x1f,
	0x59, 0xd7, 0xe3, 0xa9, 0x2a, 0x4e, 0xa6, 0xaa, 0xf8, 0x3e, 0x55, 0xc5, 0xd7, 0x99, 0x2a, 0x4c,
	0x66, 0xaa, 0xf0, 0x36, 0x53, 0x85, 0x87, 0x63, 0xec, 0xb1, 0xee, 0xc0, 0x31, 0x5c, 0xe2, 0x83,
	0x66, 0x56, 0x91, 0x45, 0x68, 0x0a, 0xb2, 0xe2, 0x3d, 0x01, 0x77, 0x78, 0xc4, 0xbb, 0xc7, 0x46,
	0x21, 0xa2, 0x4e, 0x29, 0x2b, 0xcc, 0xe9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x29, 0x85, 0xab,
	0x8c, 0x98, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GovContractAddresses) > 0 {
		for iNdEx := len(m.GovContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.GovContractAddresses[iNdEx])
			copy(dAtA[i:], m.GovContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.GovContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.StakingContractAddresses) > 0 {
		for iNdEx := len(m.StakingContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.StakingContractAddresses[iNdEx])
			copy(dAtA[i:], m.StakingContractAddresses[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.StakingContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ContractGasLimit != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ContractGasLimit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.StakingContractAddresses) > 0 {
		for _, s := range m.StakingContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GovContractAddresses) > 0 {
		for _, s := range m.GovContractAddresses {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ContractGasLimit != 0 {
		n += 1 + sovGenesis(uint64(m.ContractGasLimit))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingContractAddresses = append(m.StakingContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GovContractAddresses = append(m.GovContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractGasLimit", wireType)
			}
			m.ContractGasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ContractGasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
