version: v2

clean: true

inputs:
  - directory: .

plugins:
  - remote: buf.build/community/google-gnostic-openapi:v0.7.1
    out: ./gen/internal
    include_imports: true
    opt:
      - default_response=true
      - fq_schema_naming=false
      - title=Juno REST API
      - version=v30.0.0
      - Mjuno/clock/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/clock/module/v1
      - Mjuno/cwhooks/module/v2/module.proto=github.com/CosmosContracts/juno/v31/api/juno/cwhooks/module/v2
      - Mjuno/drip/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/drip/module/v1
      - Mjuno/feepay/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/feepay/module/v1
      - Mjuno/feeshare/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/feeshare/module/v1
      - Mjuno/mint/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/mint/module/v1
      - Mjuno/stream/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/stream/module/v1
      - Mjuno/feemarket/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/juno/feemarket/module/v1
      - Mosmosis/tokenfactory/module/v1/module.proto=github.com/CosmosContracts/juno/v31/api/osmosis/tokenfactory/module/v1
