// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: juno/clock/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryContractModules is the request type for the
// Query/QueryContractModules RPC method.
type QueryContractModules struct {
}

func (m *QueryContractModules) Reset()         { *m = QueryContractModules{} }
func (m *QueryContractModules) String() string { return proto.CompactTextString(m) }
func (*QueryContractModules) ProtoMessage()    {}
func (*QueryContractModules) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da208f579d775c8, []int{0}
}
func (m *QueryContractModules) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractModules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractModules.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractModules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractModules.Merge(m, src)
}
func (m *QueryContractModules) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractModules) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractModules.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractModules proto.InternalMessageInfo

// QueryContractModulesResponse is the response type for the
// Query/ContractModules RPC method.
type QueryContractModulesResponse struct {
	ContractAddresses []string `protobuf:"bytes,1,rep,name=contract_addresses,json=contractAddresses,proto3" json:"contract_addresses,omitempty" yaml:"contract_addresses"`
}

func (m *QueryContractModulesResponse) Reset()         { *m = QueryContractModulesResponse{} }
func (m *QueryContractModulesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryContractModulesResponse) ProtoMessage()    {}
func (*QueryContractModulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7da208f579d775c8, []int{1}
}
func (m *QueryContractModulesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryContractModulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryContractModulesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryContractModulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContractModulesResponse.Merge(m, src)
}
func (m *QueryContractModulesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryContractModulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContractModulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContractModulesResponse proto.InternalMessageInfo

func (m *QueryContractModulesResponse) GetContractAddresses() []string {
	if m != nil {
		return m.ContractAddresses
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryContractModules)(nil), "juno.clock.v1.QueryContractModules")
	proto.RegisterType((*QueryContractModulesResponse)(nil), "juno.clock.v1.QueryContractModulesResponse")
}

func init() { proto.RegisterFile("juno/clock/v1/query.proto", fileDescriptor_7da208f579d775c8) }

var fileDescriptor_7da208f579d775c8 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4b, 0xfb, 0x40,
	0x14, 0xc7, 0x7b, 0xbf, 0x1f, 0x0a, 0x06, 0x44, 0x0c, 0x45, 0xda, 0x50, 0xae, 0x25, 0x2e, 0x82,
	0x7a, 0x47, 0x74, 0x13, 0x1c, 0x6c, 0x07, 0x27, 0x07, 0x3b, 0xba, 0xc8, 0xe5, 0x7a, 0xc4, 0x68,
	0x72, 0x2f, 0xe6, 0x5d, 0x8a, 0x59, 0x05, 0x37, 0x41, 0xc1, 0x7f, 0xca, 0xb1, 0xe0, 0xe2, 0x54,
	0xa4, 0x75, 0x72, 0xf4, 0x2f, 0x90, 0xa6, 0xcd, 0x50, 0xdb, 0xc1, 0xed, 0x78, 0x9f, 0x2f, 0xef,
	0x7d, 0xee, 0x3d, 0xab, 0x7e, 0x9d, 0x69, 0xe0, 0x32, 0x02, 0x79, 0xc3, 0xfb, 0x1e, 0xbf, 0xcd,
	0x54, 0x9a, 0xb3, 0x24, 0x05, 0x03, 0xf6, 0xfa, 0x04, 0xb1, 0x02, 0xb1, 0xbe, 0xe7, 0x54, 0x03,
	0x08, 0xa0, 0x20, 0x7c, 0xf2, 0x9a, 0x86, 0x9c, 0x46, 0x00, 0x10, 0x44, 0x8a, 0x8b, 0x24, 0xe4,
	0x42, 0x6b, 0x30, 0xc2, 0x84, 0xa0, 0x71, 0x46, 0xa9, 0x04, 0x8c, 0x01, 0xb9, 0x2f, 0x50, 0xf1,
	0xbe, 0xe7, 0x2b, 0x23, 0x3c, 0x2e, 0x21, 0xd4, 0x53, 0xee, 0x6e, 0x59, 0xd5, 0xf3, 0xc9, 0xc4,
	0x0e, 0x68, 0x93, 0x0a, 0x69, 0xce, 0xa0, 0x97, 0x45, 0x0a, 0xdd, 0x47, 0x62, 0x35, 0x96, 0x81,
	0xae, 0xc2, 0x04, 0x34, 0x2a, 0x3b, 0xb2, 0x6c, 0x39, 0x43, 0x97, 0xa2, 0xd7, 0x4b, 0x15, 0xa2,
	0xc2, 0x1a, 0x69, 0xfd, 0xdf, 0x59, 0x6b, 0x1f, 0x7f, 0x0d, 0x9b, 0x8d, 0x45, 0xba, 0x07, 0x71,
	0x68, 0x54, 0x9c, 0x98, 0xfc, 0x7b, 0xd8, 0xac, 0xe7, 0x22, 0x8e, 0x8e, 0xdc, 0xc5, 0x94, 0xdb,
	0xdd, 0x2c, 0x8b, 0x27, 0x65, 0xed, 0xe0, 0x89, 0x58, 0x2b, 0x85, 0x8e, 0xfd, 0x40, 0xac, 0x8d,
	0x5f, 0x4e, 0xf6, 0x36, 0x9b, 0x5b, 0x14, 0x5b, 0x26, 0xee, 0xec, 0xfe, 0x21, 0x54, 0xfe, 0xce,
	0x6d, 0xdd, 0xbf, 0x7d, 0xbe, 0xfc, 0x73, 0xec, 0x1a, 0x9f, 0xbf, 0x4e, 0x69, 0x86, 0xed, 0xd3,
	0xd7, 0x11, 0x25, 0x83, 0x11, 0x25, 0x1f, 0x23, 0x4a, 0x9e, 0xc7, 0xb4, 0x32, 0x18, 0xd3, 0xca,
	0xfb, 0x98, 0x56, 0x2e, 0xf6, 0x83, 0xd0, 0x5c, 0x65, 0x3e, 0x93, 0x10, 0xf3, 0x4e, 0xb1, 0xfd,
	0x72, 0x0a, 0x4e, 0xbb, 0xdd, 0xcd, 0xfa, 0x99, 0x3c, 0x51, 0xe8, 0xaf, 0x16, 0x87, 0x38, 0xfc,
	0x09, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x4b, 0x54, 0x46, 0x08, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// ContractModules
	ContractModules(ctx context.Context, in *QueryContractModules, opts ...grpc.CallOption) (*QueryContractModulesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) ContractModules(ctx context.Context, in *QueryContractModules, opts ...grpc.CallOption) (*QueryContractModulesResponse, error) {
	out := new(QueryContractModulesResponse)
	err := c.cc.Invoke(ctx, "/juno.clock.v1.Query/ContractModules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// ContractModules
	ContractModules(context.Context, *QueryContractModules) (*QueryContractModulesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) ContractModules(ctx context.Context, req *QueryContractModules) (*QueryContractModulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractModules not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_ContractModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryContractModules)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ContractModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/juno.clock.v1.Query/ContractModules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ContractModules(ctx, req.(*QueryContractModules))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "juno.clock.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContractModules",
			Handler:    _Query_ContractModules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/clock/v1/query.proto",
}

func (m *QueryContractModules) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractModules) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractModules) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryContractModulesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryContractModulesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryContractModulesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ContractAddresses) > 0 {
		for iNdEx := len(m.ContractAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ContractAddresses[iNdEx])
			copy(dAtA[i:], m.ContractAddresses[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.ContractAddresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryContractModules) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryContractModulesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ContractAddresses) > 0 {
		for _, s := range m.ContractAddresses {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryContractModules) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractModules: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractModules: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryContractModulesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryContractModulesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryContractModulesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddresses = append(m.ContractAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
