// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: juno/feepay/v1/tx.proto

package feepayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_RegisterFeePayContract_FullMethodName          = "/juno.feepay.v1.Msg/RegisterFeePayContract"
	Msg_UnregisterFeePayContract_FullMethodName        = "/juno.feepay.v1.Msg/UnregisterFeePayContract"
	Msg_FundFeePayContract_FullMethodName              = "/juno.feepay.v1.Msg/FundFeePayContract"
	Msg_UpdateFeePayContractWalletLimit_FullMethodName = "/juno.feepay.v1.Msg/UpdateFeePayContractWalletLimit"
	Msg_UpdateParams_FullMethodName                    = "/juno.feepay.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the fees Msg service.
type MsgClient interface {
	// RegisterFeeShare registers a new contract for receiving transaction fees
	RegisterFeePayContract(ctx context.Context, in *MsgRegisterFeePayContract, opts ...grpc.CallOption) (*MsgRegisterFeePayContractResponse, error)
	// UnregisterFeeShare unregisters a contract for receiving transaction fees
	UnregisterFeePayContract(ctx context.Context, in *MsgUnregisterFeePayContract, opts ...grpc.CallOption) (*MsgUnregisterFeePayContractResponse, error)
	// Fund a fee pay contract
	FundFeePayContract(ctx context.Context, in *MsgFundFeePayContract, opts ...grpc.CallOption) (*MsgFundFeePayContractResponse, error)
	// Update a fee pay contract wallet limit
	UpdateFeePayContractWalletLimit(ctx context.Context, in *MsgUpdateFeePayContractWalletLimit, opts ...grpc.CallOption) (*MsgUpdateFeePayContractWalletLimitResponse, error)
	// Update the params of the module through gov v1 type.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterFeePayContract(ctx context.Context, in *MsgRegisterFeePayContract, opts ...grpc.CallOption) (*MsgRegisterFeePayContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgRegisterFeePayContractResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterFeePayContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterFeePayContract(ctx context.Context, in *MsgUnregisterFeePayContract, opts ...grpc.CallOption) (*MsgUnregisterFeePayContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUnregisterFeePayContractResponse)
	err := c.cc.Invoke(ctx, Msg_UnregisterFeePayContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FundFeePayContract(ctx context.Context, in *MsgFundFeePayContract, opts ...grpc.CallOption) (*MsgFundFeePayContractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgFundFeePayContractResponse)
	err := c.cc.Invoke(ctx, Msg_FundFeePayContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateFeePayContractWalletLimit(ctx context.Context, in *MsgUpdateFeePayContractWalletLimit, opts ...grpc.CallOption) (*MsgUpdateFeePayContractWalletLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateFeePayContractWalletLimitResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateFeePayContractWalletLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the fees Msg service.
type MsgServer interface {
	// RegisterFeeShare registers a new contract for receiving transaction fees
	RegisterFeePayContract(context.Context, *MsgRegisterFeePayContract) (*MsgRegisterFeePayContractResponse, error)
	// UnregisterFeeShare unregisters a contract for receiving transaction fees
	UnregisterFeePayContract(context.Context, *MsgUnregisterFeePayContract) (*MsgUnregisterFeePayContractResponse, error)
	// Fund a fee pay contract
	FundFeePayContract(context.Context, *MsgFundFeePayContract) (*MsgFundFeePayContractResponse, error)
	// Update a fee pay contract wallet limit
	UpdateFeePayContractWalletLimit(context.Context, *MsgUpdateFeePayContractWalletLimit) (*MsgUpdateFeePayContractWalletLimitResponse, error)
	// Update the params of the module through gov v1 type.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) RegisterFeePayContract(context.Context, *MsgRegisterFeePayContract) (*MsgRegisterFeePayContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFeePayContract not implemented")
}
func (UnimplementedMsgServer) UnregisterFeePayContract(context.Context, *MsgUnregisterFeePayContract) (*MsgUnregisterFeePayContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterFeePayContract not implemented")
}
func (UnimplementedMsgServer) FundFeePayContract(context.Context, *MsgFundFeePayContract) (*MsgFundFeePayContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FundFeePayContract not implemented")
}
func (UnimplementedMsgServer) UpdateFeePayContractWalletLimit(context.Context, *MsgUpdateFeePayContractWalletLimit) (*MsgUpdateFeePayContractWalletLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeePayContractWalletLimit not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_RegisterFeePayContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterFeePayContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterFeePayContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterFeePayContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterFeePayContract(ctx, req.(*MsgRegisterFeePayContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterFeePayContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterFeePayContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterFeePayContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnregisterFeePayContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterFeePayContract(ctx, req.(*MsgUnregisterFeePayContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FundFeePayContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFundFeePayContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FundFeePayContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FundFeePayContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FundFeePayContract(ctx, req.(*MsgFundFeePayContract))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateFeePayContractWalletLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateFeePayContractWalletLimit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateFeePayContractWalletLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateFeePayContractWalletLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateFeePayContractWalletLimit(ctx, req.(*MsgUpdateFeePayContractWalletLimit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "juno.feepay.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFeePayContract",
			Handler:    _Msg_RegisterFeePayContract_Handler,
		},
		{
			MethodName: "UnregisterFeePayContract",
			Handler:    _Msg_UnregisterFeePayContract_Handler,
		},
		{
			MethodName: "FundFeePayContract",
			Handler:    _Msg_FundFeePayContract_Handler,
		},
		{
			MethodName: "UpdateFeePayContractWalletLimit",
			Handler:    _Msg_UpdateFeePayContractWalletLimit_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "juno/feepay/v1/tx.proto",
}
